[tool.poetry]
name = "chess-analyzer-backend"
version = "1.0.0"
description = "Backend for Chess Analyzer"
authors = ["Subhajit"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.115.5"
uvicorn = {extras = ["standard"], version = "0.32.0"}
python-chess = "1.999"
stockfish = "3.28.0"
httpx = "0.27.2"
openai = "1.54.4"
python-dotenv = "1.0.1"
pydantic = "2.9.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
